name: My First GitHub Action Workflow

on:
  workflow_dispatch:

env:
  APP_NAME: Devops-shack-App

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: development

    steps:
      - name: Print Variable
        run: |
          echo "Application is $APP_NAME"
          echo "Environment: $ENVIRONMENT"

  second_demo:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: development

    steps:
      - name: Print Variable
        run: |
          echo "Application is $APP_NAME"
          echo "Environment: $ENVIRONMENT"

  
 




