name: My First GitHub Action Workflow

on: 
  workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest

     steps:
       - name: Print Hello
         run: echo "Hello from GitHub Actions"

       - name: Checkout repository
         uses: actions/checkout@v7
         
       - name: Show repository
         run: ls -la 

         
       - name: Print message 
         run: echo "Hello"
         
       - name: Print Hi
         run: echo "Hi"
         
       - name: Print bye
         run: |
            pwd
            ls -la
            whoami






