name: My First GitHub Action Workflow

on: 
  workflow_dispatch:

env:
  APP_NAME: Devops-shack-App

jobs:
  demo:
     runs-on: ubuntu-latest

     steps:
       - name: Show Print Variable
         run: echo "Application is $APP_NAME"
          




